CC=g++
SRC=./src
OBJ=./obj
INC=./inc
ex1_1 : $(SRC)/ex1_1.cpp
	$(CC) -o $(OBJ)/ex1_1 $(SRC)/ex1_1.cpp

ex1_2 : $(SRC)/ex1_2.cpp
	$(CC) -o $(OBJ)/ex1_2 $(SRC)/ex1_2.cpp

ex1_3 : $(SRC)/ex1_3.cpp
	$(CC) -o $(OBJ)/ex1_3 $(SRC)/ex1_3.cpp

ex1_4 : $(SRC)/ex1_4.cpp
	$(CC) -o $(OBJ)/ex1_4 $(SRC)/ex1_4.cpp

clean:
	rm $(OBJ)/*

all: ex1_1 ex1_2 ex1_3 ex1_4
